name: why not.
favicon: null
layout_spectrum: 0.30762
typography_spectrum: 0.0985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75639845-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#171717'
    - '#979797'
    - '#b7b7b7'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
