name: why not.
favicon: null
layout_spectrum: 0.19577039498835802
typography_spectrum: 0.5682605563197285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7336741385515779
  lightness: 0.5669236620888114
  saturation: 0.3471564636565745
  rhythmicContrast: 0.6795496835839003
purpose: []
